services:
  - type: web
    name: finance-app
    env: python
    buildCommand: "cd finance && pip install -r requirements.txt"
    startCommand: "cd finance && gunicorn finance.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: finance.settings
