# Generated by Django 5.2.5 on 2025-08-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financetrack', '0002_rename_transactions_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
